"""add structured fields to knowledge_rule

Revision ID: a5a93b790558
Revises: 001_initial
Create Date: 2026-05-21 10:10:55.640543
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a93b790558'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_rule', sa.Column('rule_code', sa.String(length=64), nullable=True))
    op.add_column('knowledge_rule', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('knowledge_rule', sa.Column('severity', sa.String(length=16), nullable=True))
    op.add_column('knowledge_rule', sa.Column('condition', sa.String(length=255), nullable=True))
    op.add_column('knowledge_rule', sa.Column('is_executable', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.create_unique_constraint(None, 'knowledge_rule', ['rule_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_rule', type_='unique')
    op.drop_column('knowledge_rule', 'is_executable')
    op.drop_column('knowledge_rule', 'condition')
    op.drop_column('knowledge_rule', 'severity')
    op.drop_column('knowledge_rule', 'threshold')
    op.drop_column('knowledge_rule', 'rule_code')
    # ### end Alembic commands ###
